### PR TITLE
Create sus.fstop

### PR DESCRIPTION
**Pull request by MrKomodoDragon**

### CODE REVIEW

**Comment by jay3332** [comment]
invalid syntax (lowercase as 🐓)

**Comment by Tom-the-Bomb** [comment]
u forgot the coords for text

**Comment by Tom-the-Bomb** [comment]
AMSHSMSH

**Comment by jay3332** [comment]
SMHSMSH

**Comment by MrKomodoDragon** [comment]
i added coords now
>:(

**Pull request merged**
